[features]
seeds = false
skip-lint = false

[programs.localnet]
cp_amm = "cpamdpZCGKUy5JxQXB4dcpGPiikHawvSWAd6mEn1sGG"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "keys/local/admin-bossj3JvwiNK7pvjr149DqdtJxf2gdygbcmEPTkb2F1.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[toolchain]
anchor_version = "0.31.0"
solana_version = "2.1.0"
