[features]
seeds = false
skip-lint = false

[programs.localnet]
lottery = "StkraNY8rELLLoDHmVg8Di8DKTLbE8yAWZqRR9w413n"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
client = "yarn run ts-node client/*.ts"
